### ISSUE TITLE
Block quote syntax (>>>) has been deprecated

### ISSUE THREAD

**Issue by anibalsanchez** [getgrav/grav-plugin-markdown-notices#1]
Hi,

I have just noticed (:-D) that >>> notices has been deprecated... but the new plugin does not offer the same Tip,Note,etc structures.

Do you plan to add it?

PD: Grav is great!

Regards,

**Comment by rhukster** [comment]
Sorry for the late reply, I missed this one!

the >>>> is not deprecated per say, it's still in the antimatter CSS for example.  However, this new markdown syntax allows you to use the notices in any theme as it provides its own CSS and uses a simpler `<div>` structure rather than relying on the nested `blockquote` as before.

The styling provided by this comes from the CSS and mimics the styling in Antimatter.  Learn2 has the tips/note/etc text added (again from CSS only), and both methods are supported in learn2 theme now.  If you want to port it to another theme, you would just have to update the CSS as it is in learn2.
